name: astra
description: A wallpaper app built with flutter.
publish_to: 'none'
version: 0.3.0+4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  http:
  cached_network_image:
  async_wallpaper:
  url_launcher:
  flutter_staggered_animations:
  animations:
  get:
  package_info_plus:
  transparent_image:
  collection: 
  loading_indicator:
  shared_preferences:
  flutter_native_splash:
  flutter_carousel_widget:
  persistent_bottom_nav_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - shorebird.yaml
  fonts:
    - family: Tanglewoods
      fonts:
        - asset: assets/fonts/Tanglewoods.otf