name: pixelverse
description: A wallpaper app built with flutter.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  http:
  cached_network_image:
  async_wallpaper:
  url_launcher:
  flutter_staggered_animations:
  animations:
  get:
  progressive_image:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons:

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FBECFF"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FBECFF"
    theme_color: "#4FC3F7"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"